name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./Containers --file Containers/Dockerfile --tag my-image-name:$(date +%s)
    - name: List Docker images
      run: docker images

    - name: Publish Docker image to GitHub Container Registry
      uses: docker/build-push-action@v3
      with:
        context: ./Containers
        file: Containers/Dockerfile
        push: true
        tags: github.com/${{secrets.DOCKER_USERNAME}}/my-image-name:latest
